rules:
  - type: arm
    mode: prefix
    patterns:
      - "DESKTOP-"
      - "LAPTOP-"

  - type: mkp
    mode: contains
    patterns:
      - "iPhone"
      - "Tab-A9-"

  - type: router
    mode: regex
    patterns:
      - "^[gisy][0-9]{9}$"

default: unknown
options:
  case_insensitive: true
  trim: true
